SaoPerolasWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('restricted/', views.restricted_view, name="restricted"),
    path('', views.saved_products, name='index_accounts'),
    path('add_to_favourites', views.add_to_favourites, name="add_to_favourites"),
    path('saved_products', views.saved_products, name="saved_products"),
    path('user_info', views.user_info, name="user_info"),
    path('delete_all_users', views.delete_all_users, name="delete_all_users"),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('add/product<int:id>', views.add_to_cart, name="add_to_cart"),
    path('remove/product<int:id>', views.remove_from_cart, name="remove_from_cart"),
    path('increase/product<int:id>', views.increase_quantity,name="increase_quantity"),
    path('display/', views.display_cart, name="display_cart"),
    path('handler/', views.shipping_details, name="shipping_details"),
    path('details/', views.order_details, name="order_details"),
    path('', views.display_cart, name="index-cart"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from products.models import Product
from cart.models import ShippingDetails

# Create your models here.
User = get_user_model()

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favourite_products = models.ManyToManyField(Product, blank=True)
    anonymous_user = models.BooleanField(default=False)
    use_saved_details = models.BooleanField(default=False)
    shipping_details_id = models.CharField(max_length=40)
    # Should have just used shipping details model
    email = models.EmailField(max_length=70,blank=True)
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    city = models.CharField(max_length=40)
    country = models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    zip_code = models.CharField(max_length=40)
    localidade = models.CharField(max_length=40)
    cell_number = models.CharField(max_length=40)

    def __str__(self):
        return self.user.username

def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)

post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from cart.models import Cart
from products.models import Product

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        if(request.POST["password1"] != request.POST["password2"]):
            return render(request, 'accounts/signup.html', {'error': 'As passwords não são iguais'})
        try:
            user = User.objects.create_user(((request.POST['email']).split("@"))[0], request.POST['email'], request.POST["password1"])
        except Exception as e:
            return render(request, 'accounts/signup.html', {'error': 'Já existe uma conta com esse email'})
        user.save()
        user.cart = Cart(id=0, total_price=0, user=user)
        user.userprofile.name = request.POST['first_name']
        user.userprofile.last_name = request.POST['last_name']
        user.userprofile.country = request.POST['country']
        user.userprofile.address = request.POST['address']
        user.userprofile.city = request.POST['city']
        user.userprofile.zip_code = request.POST['zip_code']
        user.userprofile.localidade = request.POST['localidade']
        user.userprofile.cell_number = request.POST['cell_number']
        user.userprofile.email = request.POST['email']
        user.save()
        user.userprofile.save()
        login(request, user)
        return redirect('index_accounts')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        try:
            user = User.objects.get(email=email)
        except Exception as e:
            return render(request, 'accounts/login.html', {'error': 'Não há utilizador com esse email ou a palavra passe está errada'})
        authenticated = authenticate(username=user.username, password=password)
        if authenticated is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('index_accounts')
        else:
            return redirect('index_accounts')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index_accounts')

@login_required
def add_to_favourites(request):
    if request.method == 'POST':
        id = request.POST['id']
        user = request.user.userprofile
        user.favourite_products.add(Product.objects.get(id=id))
    return redirect(saved_products)

@login_required
def user_info(request):
    if request.method == 'POST':
        if request.POST['first_name']:
            request.user.userprofile.name = request.POST['first_name']
        if request.POST['last_name']:
            request.user.userprofile.last_name = request.POST['last_name']
        if request.POST['country']:
            request.user.userprofile.country = request.POST['country']
        if request.POST['address']:
            request.user.userprofile.address = request.POST['address']
        if request.POST['city']:
            request.user.userprofile.city = request.POST['city']
        if request.POST['zip_code']:
            request.user.userprofile.zip_code = request.POST['zip_code']
        if request.POST['localidade']:
            request.user.userprofile.localidade = request.POST['localidade']
        if request.POST['cell_number']:
            request.user.userprofile.cell_number = request.POST['cell_number']
        if request.POST['email']:
            request.user.userprofile.email = request.POST['email']
        request.user.userprofile.save()
        return render(request, 'accounts/sucessfulChange.html')
    else:
        user = request.user
        context = {'user' : user}
        return render(request, 'accounts/user_info.html', context)

@login_required
def saved_products(request):
    user = request.user
    context = {'favourite_products': user.userprofile.favourite_products}
    return render(request, 'accounts/saved_products.html', context)

@login_required(login_url="/accounts/login/")
def restricted_view(request):
    return render(request, 'accounts/restrictedAcess.html')

def index_accounts(request):
    return render(request, 'accounts/index_accounts.html')


def delete_all_users(request):
    if( "HTTP_INEEDTODELETEUSERS" in dict(request.META.items())):
        for user in User.objects.all():
            if(user.userprofile.anonymous_user == True):
                logout(user)
                user.delete()
        return HttpResponse("Users deleted")
    else:
        return HttpResponse("No Header")

accounts/templates/accounts/base_layout.html
{% load static %}
<!DOCTYPE html>

<html>

<head>

  <meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1">

  <title>São Pérolas | Colares</title>

  <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
<meta name="theme-color" content="#ffffff">
<meta name="description" content="É uma marca registada que trabalha com as tradicionais pérolas com uma abordagem contemporânea !!">
<meta name="keywords" content="Colares, perolas, sao perolas, colares, são pérolas, São pérolas, São Pérolas">
<meta name="author" content="João Maria Janeiro">
  <style>

  .pull-left img{

    padding-top: 4px;

    padding-left: 4px;

    height: 45px;

  }
  .container-fluid{

    background-color: #ffffff;

  }

  .site-form{
    margin-top: 60px;
    padding: 20px;
    margin-bottom: 20px;
  }
  .site-form input, .site-form textarea{
    display: block;
  }

  .helptext, .helptext ul{
    margin: 0 auto 20px;
    color: #bbb;
    font-size: 0.9em;
    display: block;
  }
  .errorlist li{
    padding: 10px;
    list-style-type: none;
    border: 1px solid #ff5722;
    color: #ff5722;
    margin: 10 px 0;
  }
  .errorlist{
    padding: 0;
  }
  .site-form input[type="submit"]{
    margin-top: 20px;
  }
  </style>

      <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">




</head>

<body>


  <div class="container">
    <!-- .navbar-fixed-top, or .navbar-fixed-bottom can be added to keep the nav bar fixed on the screen -->
    <nav class="navbar-default navbar-fixed-top">
      <div class="container-fluid">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

          <!-- Button that toggles the navbar on and off on small screens -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

          <!-- Hides information from screen readers -->
            <span class="sr-only"></span>

            <!-- Draws 3 bars in navbar button when in small mode -->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- You'll have to add padding in your image on the top and right of a few pixels (CSS Styling will break the navbar) -->
          <a class="pull-left" href="{% url 'index' %}"><img src="{% static 'img/favicon.png' %}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}">Home<span class="sr-only"></span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produtos <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="dropdown-submenu">
               <a tabindex="-1" href="#">Colares</a>
               <ul class="dropdown-menu">
                 <li><a tabindex="-1" href="{% url 'products' %}">Compridos</a></li>
                 <li><a href="curtos.html">Curtos</a></li>
                 <li><a href="#">Fios</a></li>
                 <li role="separator" class="divider"></li>
               </ul>
             </li>
                <li><a href="{% url 'index_pulseira' %}">Pulseiras</a></li>
                <li><a href="{% url 'index_brincos' %}">Brincos</a></li>
              </ul>
            </li>
            <li><a href="{% url 'contactos' %}" data-toggle="tooltip" data-placement="left" title="">Contactos</a></li>
            <li><a href="{% url 'index-cart' %}"><img src="{% static 'img/malinha.png' %}" border="0" width="15" height="20"></a></li>
            {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-regular" type="submit">Logout</button>
              </form>
            </li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Signup</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    </div>
    <br>
    <br>



    <br>
    <br>

<div class="container">


{% block content %}
{% endblock %}

</div>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

     <script src="{% static 'bootstrap.min.js' %}"></script>

</body>

</html>

accounts/templates/accounts/index_accounts.html
{% extends 'accounts/base_layout.html' %}

{% block content %}
<h1>INDEX</h1>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'products/layout.html' %}
{% load static %}

{% block content %}
<br>
<br>
{% if user.is_authenticated %}
<h2> You are already logged in {{ user.username }}</h2>

{% else %}

<div class="container">
      <br>
      <br>
      <br>
      <div class="row">
        <div class="col-md-6">
          <h3 style="color:gray;" >Já sou utilizador São Pérolas.</h3>
          <p style="color:gray;">Introduza o seu email e a sua palavra-passe para se identificar.</p>
          <form id="login-form" method="post" action="{% url 'login' %}">
              {% csrf_token %}
              <table class="table">
                  <tr>
                      <td><input id="id_email" name="email"
                                 type="text" class="form-control" placeholder="Introduza aqui o seu email"></td>
                  </tr>
                  <tr>
                      <td><input id="id_password" name="password"
                                 type="password" class="form-control" placeholder="Password"></td>
                  </tr>
              </table>
              {% if form.errors %}
                  <p class=" label label-danger">
                      Your username and password didn't match.
                      Please try again.
                  </p>
              {% endif %}
              {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
              {% endif %}
              <button class="btn btn-secondary" type="submit" name="button" value="Login">INICIAR SESSÃO</button>

          </form>
          {% if error %}
          <p>{{error}}</p>
          {% endif %}
        </div>
        <div class="col-md-6">
            <h3 style="color:gray;">Quero ser utilizador São Pérolas</h3>
            <p style="color:gray;">Se ainda não tem uma conta de usuário de São Pérolas.pt utilize esta opção para aceder ao formulário de registo.</p>
            <br>
            <p style="color:gray;">Solicitar-lhe-emos a informação imprescindível para agilizar o processo de compra.</p>
            <br>
            <a href="{% url 'signup' %}"><button type="submit" class="btn btn-secondary">CRIAR CONTA</button></a>
      </div>
    </div>

    <br><br><br><br><br><br>


    {% endif %}
{% endblock %}

accounts/templates/accounts/restrictedAcess.html
{% extends 'accounts/base_layout.html' %}

{% block content %}
<br>
<br>
<h1> Restricted </h1>
{% if user.is_authenticated %}
<h2> Hello {{ user.username }}</h2>
{% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'products/layout.html' %}
{% load static %}

{% block content %}
<br>
<br>

{% if user.is_authenticated %}
<h2> You already have an account {{ user.username }}</h2>

{% else %}

<div class="container">
      <br>
      <br>
      <h4 style="color:gray;">Escreva os seus dados pessoais</h4>
      <br>
      <br>
      {% if error %}
      <p>{{error}}</p>
      {% endif %}
      <form id="signup-form" method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <input type="email" required class="form-control"id="id_email" name="email" placeholder="Email">
          </div>
        </div>
        <br>
        <br>
        <div class="form-row">
          <div class="form-group col-md-6">
            <input required type="password" class="form-control" id="id_password1" name="password1" placeholder="Password">
          </div>
          <div class="form-group col-md-6">
            <input required type="password" class="form-control" id="id_password2" name="password2" placeholder="Repetir Password">
          </div>
        </div>
        <br>
        <br>
        <div class="form-row">
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Nome">
          </div>
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Apelidos">
          </div>
        </div>
        <br>
        <br>
        <div class="form-row">
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" id="id_country" name="country" placeholder="País">
          </div>
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" id="id_address" name="address" placeholder="Morada">
          </div>
        </div>
        <br>
        <br>
        <div class="form-row">
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" name="zip_code" id="id_zip_code" placeholder="Codigo Postal">
          </div>
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" name="city" id="id_city" placeholder="Cidade">
          </div>
        </div>
        <br>
        <br>
        <div class="form-row">
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" name="localidade" id="id_localidade" placeholder="Localidade">
          </div>
          <div class="form-group col-md-6">
            <input required type="text" class="form-control" name="cell_number" id="id_cell_number" placeholder="Telemóvel">
          </div>
        </div>

        <br>
        <br>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck" required>
            <label class="form-check-label" for="gridCheck">
              Li e entendi a Política de Privacidade
            </label>
          </div>
        </div>
        {% if form.errors %}
            <p class=" label label-danger">{{ form.errors }}</p>
        {% endif %}
        <button type="submit" value="Signup"  class="btn btn-secondary">Registar</button>
      </form>
    </div>




{% endif %}

{% endblock %}

accounts/templates/accounts/sucessfulChange.html
{% extends 'products/layout.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <br>
  <div class="alert alert-success" role="alert">
    O seu perfil doi editado com sucesso!
  </div>
</div>
{% endblock %}

accounts/templates/accounts/user_info.html
{% extends 'products/layout.html' %}
{% load static %}

{% block content %}
<br>
<br>

<div class="container">
  <br>
  <br>
  <h4 style="color:gray;">Edite os seus dados pessoais</h4>
  <br>
  <br>

  <form id="signup-form" method="post" action="{% url 'user_info' %}">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <input type="email" class="form-control"id="id_email" name="email" placeholder="{{user.userprofile.email}}">
      </div>
    </div>
    <br>
    <br>
    <div class="form-row">
      <div class="form-group col-md-6">
        <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="{{user.userprofile.name}}">
      </div>
      <div class="form-group col-md-6">
        <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="{{user.userprofile.last_name}}">
      </div>
    </div>
    <br>
    <br>
    <div class="form-row">
      <div class="form-group col-md-6">
        <input type="text" class="form-control" id="id_country" name="country" placeholder="{{user.userprofile.country}}">
      </div>
      <div class="form-group col-md-6">
        <input type="text" class="form-control" id="id_address" name="address" placeholder="{{user.userprofile.address}}">
      </div>
    </div>
    <br>
    <br>
    <div class="form-row">
      <div class="form-group col-md-6">
        <input type="text" class="form-control" name="zip_code" id="id_zip_code" placeholder="{{user.userprofile.zip_code}}">
      </div>
      <div class="form-group col-md-6">
        <input type="text" class="form-control" name="city" id="id_city" placeholder="{{user.userprofile.city}}">
      </div>
    </div>
    <br>
    <br>
    <div class="form-row">
      <div class="form-group col-md-6">
        <input  type="text" class="form-control" name="localidade" id="id_localidade" placeholder="{{user.userprofile.localidade}}">
      </div>
      <div class="form-group col-md-6">
        <input  type="text" class="form-control" name="cell_number" id="id_cell_number" placeholder="{{user.userprofile.cell_number}}">
      </div>
    </div>

    <br>
    <br>

    {% if form.errors %}
        <p class=" label label-danger">{{ form.errors }}</p>
    {% endif %}
    <button type="submit" value="Change"  class="btn btn-secondary">Editar Informações</button>
  </form>
</div>
{% endblock %}