SaoPerolasWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('add/product<int:id>', views.add_to_cart, name="add_to_cart"),
    path('remove/product<int:id>', views.remove_from_cart, name="remove_from_cart"),
    path('increase/product<int:id>', views.increase_quantity,name="increase_quantity"),
    path('display/', views.display_cart, name="display_cart"),
    path('handler/', views.shipping_details, name="shipping_details"),
    path('details/', views.order_details, name="order_details"),
    path('', views.display_cart, name="index-cart"),
]

products/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/colares/colar<int:id>/', views.colares, name='colares'),
    path('products/pulseiras/', views.pulseiras, name='index_pulseira'),
    path('products/pulseiras/pulseira<int:id>/', views.pulseira_individual, name='pulseira_individual'),
    path('contactos', views.contactos, name='contactos'),
    path('products/brincos/', views.brincos, name='index_brincos'),
    path('products/brincos/brinco<int:id>/', views.brinco_individual, name='brinco_individual'),
    path('products/create', views.product_create, name="create_product"),
]

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=400)
    description = models.TextField()
    price = models.CharField(max_length=5)
    image = models.FileField(upload_to='page_image', blank=True)
    pulseira = models.BooleanField()
    brinco = models.BooleanField()
    colar = models.BooleanField()

    def __str__(self):
        return 'Name: {}, ID: {}'.format(self.name, self.id)

class BackGroundImage(models.Model):
    image = models.FileField(upload_to='background', blank=True)

products/forms.py
from django import forms
from .models import Product

class CreateProduct(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image', 'colar', 'pulseira', 'brinco')

products/views.py
from django.shortcuts import render, redirect
from .models import Product, BackGroundImage
from .forms import CreateProduct
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    image = BackGroundImage.objects.order_by('id')
    try:
        imagez = image[0]
        colar = image[1]
        pulseira = image[2]
        brinco = image[3]
    except Exception as e:
        print(e)
    context = {'image': imagez, 'colar': colar, 'pulseira': pulseira, 'brinco': brinco}
    return render(request, 'products/index.html', context)

def products(request):
    colar = Product.objects.order_by('-id')

    context = {'colar': colar}
    return render(request, 'products/compridos.html', context)

def colares(request, id):
    colar = Product.objects.get(id=id)
    context = {'colar': colar}
    return render(request, 'products/product_page.html', context)

def pulseiras(request):
    pulseira = Product.objects.order_by('-id')

    context = {'pulseira': pulseira}
    return render(request, 'products/pulseiras.html', context)

def pulseira_individual(request, id):
    pulseira = Product.objects.get(id=id)
    context = {'pulseira': pulseira}
    return render(request, 'products/pulseira.html', context)

def contactos(request):
    return render(request, 'products/contactos.html')

def brincos(request):
    brinco = Product.objects.order_by('-id')

    context = {'brinco': brinco}
    return render(request, 'products/brincos.html', context)

def brinco_individual(request, id):
    brinco = Product.objects.get(id=id)
    context = {'brinco': brinco}
    return render(request, 'products/brinco.html', context)


@login_required(login_url="/accounts/login/")
def product_create(request):
    if request.method == 'POST':
        form = CreateProduct(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            try:
                if(request.POST['colar'] == "on"):
                    colar = True
            except MultiValueDictKeyError:
                colar = False
            try:
                if(request.POST['pulseira'] == "on"):
                    pulseira = True
            except MultiValueDictKeyError:
                pulseira = False
            try:
                if(request.POST['brinco'] == "on"):
                    brinco = True
            except MultiValueDictKeyError:
                brinco = False


            price=request.POST['price']
            a=price.split()
            a.reverse()
            price = int(" ".join(a))

            print("I GOT HERE")
            new_product = Product(name=request.POST['name'], description=request.POST['description'], price=price, image=request.FILES['image'], colar=colar, brinco=brinco, pulseira=pulseira)
            print("I GOT FURTHER")
            try:
                new_product.save()
            except Exception as e:
                print(e)

            return redirect('products')
        else:
            print (form.errors)
            return HttpResponse('Error occurred, product was not added' + str(form.errors))
    else:
        form = CreateProduct()
        return render(request, 'products/create_product.html', {'form': form})

products/templates/products/brinco.html
{% extends 'products/layout.html' %}
{% load static %}


{% block content %}
<br>
<br>
<div class="container">
  <div class="row">
  <div class="col-md-6">
    <img class="img-fluid" style=" max-width: 100%; height: auto;display: block;" src="{{ brinco.image.url }}">
  </div>
      <div class="col-md-6">
        <h1>{{ brinco.name }}</h1>
        <p>{{ brinco.description }}</p>
        <p>{{ brinco.price }}€</p>

      <a href="{% url 'add_to_cart' brinco.id %}"><button class="btn btn-secondary pull-right" name="button">Adicionar ao Carrinho</button></a>
      <br><br>
            <div class="lgn-container col-lg-8">
                <form id="form" action="{% url 'add_to_favourites' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{brinco.id}}">
                    {% if form.errors %}
                        <p class=" label label-danger">
                            {{ form.errors }}
                        </p>
                    {% endif %}
                    <input type="image" name="submit" value="Add To Favourites" src="{% static 'img/heart.png' %}" width="20" />
                </form>
            </div>

      </div>
    </div>

</div>
<br><br><br>
{% endblock %}

products/templates/products/contactos.html
{% extends 'products/layout.html' %}
{% load static %}
{% block content %}
<br>
<br>
<div class="row contact">
  <div class="col-md-1 col-sm-2 col-xs-3">
    <img class="img-responsive" src="{% static 'img/fblogo_1.png' %}">
  </div>
  <div class="col-md-11">
    <a href="https://www.facebook.com/saoperolas/"><h3>Facebook</h3></a>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-sm-2 col-xs-3">
    <img class="img-responsive" src="{% static 'img/instalogo.png' %}">
  </div>
  <div class="col-md-11">
    <a href="https://www.instagram.com/sao.perolas/?hl=pt"><h3>Instagram</h3></a>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-sm-2 col-xs-3">
    <img class="img-responsive" src="{% static 'img/gmapslogo.png' %}">
  </div>
  <div class="col-md-11">
    <a href="https://goo.gl/maps/zYQMKM3QPZ52"><h3>Rua Coronel Pereira da Silva, 2B. 1300-147 Lisboa</h3></a>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-sm-2 col-xs-3">
    <img class="img-responsive" src="{% static 'img/celllogo.png' %}">
  </div>
  <div class="col-md-11">
    <a href=""><h3>960003160</h3></a>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-sm-2 col-xs-3">
    <img class="img-responsive" src="{% static 'img/maillogo.png' %}">
  </div>
  <div class="col-md-11">
    <a href="mailto:sao.perolas.pt@gmail.com"><h3>sao.perolas.pt@gmail.com</h3></a>
  </div>
</div>
{% endblock %}

products/templates/products/create_product.html
{% extends 'products/layout.html' %}


{% block style %}
@media only screen and (max-width: 600px)  {

}

{% endblock %}


{% block content %}
<br>
<br>
{% for field in form %}
  {{field.error}}
  {% endfor %}

{% if user.is_superuser %}
<h1>Crie o seu Produto</h1>
  <h2> Hello {{ user.username }}</h2>
<div id="content-container" class="container p-none">
    <div class="lgn-container col-lg-8">
        <form id="login-form" action="{% url 'create_product' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                <tr>
                    <td><label for="id_name">Name</label></td>
                    <td><input id="id_name" name="name" style="width:400px;"
                               type="text" class="form-control"></td>
                </tr>
                <tr>
                    <td><label for="id_description">Description</label></td>
                    <td><input id="id_description" name="description"
                               type="text" class="form-control"></td>
                </tr>
                <tr>
                    <td><label for="id_price">Price</label></td>
                    <td><input id="id_price" name="price"
                               type="number" class="form-control"></td>
                </tr>
                <tr>
                  <td>
                    {{ form.image }}
                  </td>
                </tr>
                <tr>
                  <td>
                    <div class="form-check">
                       <label class="form-check-label">
                         Colar: {{ form.colar }}
                       </label>
                     </div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <div class="form-check">
                       <label class="form-check-label">
                         Brinco: {{ form.brinco }}
                       </label>
                     </div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <div class="form-check">
                       <label class="form-check-label">
                         Pulseira: {{ form.pulseira }}
                       </label>
                     </div>
                  </td>
                </tr>
            </table>
            {% if form.errors %}
                <p class=" label label-danger">
                    {{ form.errors }}
                </p>
            {% endif %}
            <input type="submit" value="Update"
                   class="btn btn-primary pull-right" />
        </form>
    </div>
</div>

{% else %}
<h1>You do not have permissions to access this page</h1>
{% endif%}

{% endblock %}

products/templates/products/curto.html
{% extends 'products/layout.html' %}
{% load static %}


{% block content %}
<br>
<br>
<div class="container">
  <div class="row">
  <div class="col-md-6">
    <img class="img-fluid" style=" max-width: 100%; height: auto;display: block;" src="{{ curto.image.url }}">
  </div>
      <div class="col-md-6">
        <h1>{{ curto.name }}</h1>
        <p>{{ curto.description }}</p>
        <p>{{ curto.price }}€</p>

      <a href="{% url 'add_to_cart' curto.id %}"><button class="btn btn-secondary pull-right" name="button">Adicionar ao Carrinho</button></a>
      <br><br>
            <div class="lgn-container col-lg-8">
                <form id="form" action="{% url 'add_to_favourites' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{curto.id}}">
                    {% if form.errors %}
                        <p class=" label label-danger">
                            {{ form.errors }}
                        </p>
                    {% endif %}
                    <input type="image" name="submit" value="Add To Favourites" src="{% static 'img/heart.png' %}" width="20" />
                </form>
            </div>

      </div>
    </div>

</div>
<br><br><br>
{% endblock %}

products/templates/products/fio.html
{% extends 'products/layout.html' %}
{% load static %}


{% block content %}
<br>
<br>
<div class="container">
  <div class="row">
  <div class="col-md-6">
    <img class="img-fluid" style=" max-width: 100%; height: auto;display: block;" src="{{ fio.image.url }}">
  </div>
      <div class="col-md-6">
        <h1>{{ fio.name }}</h1>
        <p>{{ fio.description }}</p>
        <p>{{ fio.price }}€</p>

      <a href="{% url 'add_to_cart' fio.id %}"><button class="btn btn-secondary pull-right" name="button">Adicionar ao Carrinho</button></a>
      <br><br>
            <div class="lgn-container col-lg-8">
                <form id="form" action="{% url 'add_to_favourites' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{fio.id}}">
                    {% if form.errors %}
                        <p class=" label label-danger">
                            {{ form.errors }}
                        </p>
                    {% endif %}
                    <input type="image" name="submit" value="Add To Favourites" src="{% static 'img/heart.png' %}" width="20" />
                </form>
            </div>

      </div>
    </div>

</div>
<br><br><br>
{% endblock %}

products/templates/products/index.html
{% extends 'products/layout.html' %}
{% load static %}

{% block style %}
.bg-image{
  background-size:cover;
  height:100%;
  height: 91vh;
  background-attachment:scroll;
}
.tittlez{
  text-align: center;
  color: gray;
}
{% endblock %}


{% block content %}
<!-- <div class="bg-image"> -->
  <img  style="width: 100%; margin-bottom:20px;" src="{{ image.image.url }}" alt="">

    <!-- </div> -->

    <div class="container">
      <div class="tittlez">
        <br>
        <br>
        <h4>Bijuterias 2019</h4>
        <br>
      </div>
      <div class="row">
        <div class="col-md-4">
          <a href="{% url 'products' %}">
            <img width="300" src="{{colar.image.url}}" alt="">
            <p style="color:gray;">Colares</p>
          </a>
        </div>
        <div class="col-md-4">
          <a href="{% url 'index_pulseira' %}">
            <img width="300" src="{{pulseira.image.url}}" alt="">
            <p style="color:gray;">Pulseiras</p>
          </a>
        </div>
        <div class="col-md-4">
          <a href="{% url 'index_brincos' %}">
            <img width="300" src="{{brinco.image.url}}" alt="">
            <p style="color:gray;">Brincos</p>
          </a>
        </div>
      </div>
      <br>
    </div>
{% endblock %}

products/templates/products/layout.html
{% load static %}
<!DOCTYPE html>

<html>

<head>

  <meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1">

  <title>São Pérolas | Colares</title>


  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

<meta name="theme-color" content="#ffffff">
<meta name="description" content="É uma marca registada que trabalha com as tradicionais pérolas com uma abordagem contemporânea !!">
<meta name="keywords" content="Colares, perolas, sao perolas, colares, são pérolas, São pérolas, São Pérolas">
<meta name="author" content="João Maria Janeiro">
{% block style-n %}
{% endblock %}

  <style>

  .thumbnail {
    border: 0 none;
    box-shadow: none;
    width: 100%;
    overflow: hidden;
}

  @media screen and (min-width: 960px) {
    .thumbnail img{
      -webkit-transition: all 0.5s ease;
    }
    .thumbnail img:hover{
      transform: scale(1.8);
    }
  }

  .navbar-brand {
      position: absolute;
      width: 100%;
      left: 0;
      top: 5;
      text-align: center;
      margin: auto;
  }
  .navbar-toggle {
      z-index:3;
  }
  .navbar {
    min-height: 90px;
  }
  .sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #ffffff;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
  }

  .sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 15px;
    color: #818181;
    display: block;
    transition: 0.3s;
  }


  .sidenav a:hover {
    color: #f1f1f1;
  }

  .sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
  }


  @media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
  }

  @media (min-width: 768px) {
  .abs-center-x {
      position: absolute;
      left: 50%;
      transform: translateX(-50%);
  }
}

{% block style %}
{% endblock %}
  </style>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
</head>

<body>

  <div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'products' %}">Colares &emsp; &nbsp; &ensp;  ></a>
    <a href="{% url 'index_pulseira' %}">Pulseiras &emsp; &ensp; ></a>
    <a href="{% url 'index_brincos' %}">Brincos &emsp; &nbsp; &ensp; ></a>
  </div>

  <div class="sidenav" id="mySidenav2">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav2()">&times;</a>
    <a href="{% url 'saved_products' %}">Produtos Guardados </a>
    <a href="{% url 'user_info' %}">Editar Informaçoes </a>
    {% if user.is_authenticated %}
    <form class="logout-link" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button style="margin-left:30px;" class="btn btn-secondary" type="submit">Logout</button>
    </form>
    {% else %}
    <a href="{% url 'login' %}"><button type="button" class="btn btn-secondary" style="margin-left:30px;" >Iniciar Sessão</button></a>
    {% endif %}
  </div>



  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <ul class="nav navbar-nav navbar-center abs-center-x">
          <li class="nav-item"><a class="nav-link" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" width="70" ></a></li>
      </ul>
        <ul class="nav navbar-nav">
            <li class="nav-item active">
                <span class="navbar-toggler-icon" onclick="openNav()"></span>&ensp;Menu
            </li>
        </ul>
        <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" style="text-decoration:none;color:gray" href="#" onclick="openNav2()" > <i class="fas fa-user"></i> Conta</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="text-decoration:none;color:gray" href="{% url 'index-cart' %}"> <i class="fas fa-shopping-bag"></i> Cesto de Compras</a>
        </li>
      </ul>
    </div>
  </nav>


    {% block content %}
    {% endblock %}

  <footer> <center>
    <a style="color:gray;" href="https://www.instagram.com/sao.perolas/"><i style="font-size: 2em;" class="fab fa-instagram"></i></a>
    <a style="color:gray;" href="https://www.facebook.com/saoperolas"><i style="font-size: 2em;" class="fab fa-facebook-square"></i></a>
    <a style="color:gray;" href="https://api.whatsapp.com/send?phone=351960003160"><i style="font-size: 2em;" class="fab fa-whatsapp"></i></a>
    <br>
    <br>
    <img width="150PX" src="{% static 'img/graylogo.png' %}">
    <br>
    <br>
    <b style="font-size:15px;" >SHOW ROOM.</b> RUA CORONEL PEREIRA DA SILVA, 2B
    <p style="font-size:15px;" >1300-147 LISBOA, PORTUGAL</p>
    </center>
    <p style="FONT-SIZE:10px;" >DIREITOS DE AUTOR © 2019 SÃO PÉROLAS</p>
  </footer>


  {% block script%}
  {% endblock %}

  <script>

        function openNav() {
          document.getElementById("mySidenav").style.opacity = "0.8";
          document.getElementById("mySidenav").style.width = "250px";
          document.body.style.backgroundColor = "rgba(0,0,0,0.4)";

        }

        function closeNav() {
          document.getElementById("mySidenav").style.width = "0";
          document.body.style.backgroundColor = "white";

        }

        function openNav2() {
          document.getElementById("mySidenav2").style.opacity = "0.8";
          document.getElementById("mySidenav2").style.width = "250px";
          document.body.style.backgroundColor = "rgba(0,0,0,0.4)";

        }

        function closeNav2() {
          document.getElementById("mySidenav2").style.width = "0";
          document.body.style.backgroundColor = "white";

        }
        </script>
      </body>
    </html>

products/templates/products/product_page.html
{% extends 'products/layout.html' %}
{% load static %}


{% block content %}
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
          <img class="img-fluid" style=" max-width: 100%; height: auto;display: block;" src="{{ colar.image.url }}">
        </div>
        <div class="col-md-6">
          <h1>{{ colar.name }}</h1>
          <p>{{ colar.description }}</p>
          <p>{{ colar.price }}€</p>


      <a href="{% url 'add_to_cart' colar.id %}"><button class="btn btn-secondary pull-right" name="button">Adicionar ao Carrinho</button></a>
      <br><br>
          <div class="lgn-container col-lg-8">
              <form id="form" action="{% url 'add_to_favourites' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="id" value="{{colar.id}}">
                  {% if form.errors %}
                      <p class=" label label-danger">
                          {{ form.errors }}
                      </p>
                  {% endif %}
                  <input type="image" name="submit" value="Add To Favourites" src="{% static 'img/heart.png' %}" width="20" />
              </form>
          </div>

        </div>
  </div>
</div>

<br><br><br>
{% endblock %}

products/templates/products/pulseira.html
{% extends 'products/layout.html' %}
{% load static %}


{% block content %}
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img class="img-fluid" style=" max-width: 100%; height: auto;display: block;" src="{{ pulseira.image.url }}">
        </div>
        <div class="col-md-6">
          <h1>{{ pulseira.name }}</h1>
          <p>{{ pulseira.description }}</p>
          <p>{{ pulseira.price }}€</p>

      <a href="{% url 'add_to_cart' pulseira.id %}"><button class="btn btn-secondary pull-right" name="button">Adicionar ao Carrinho</button></a>
      <br><br>
            <div class="lgn-container col-lg-8">
                <form id="form" action="{% url 'add_to_favourites' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{pulseira.id}}">
                    {% if form.errors %}
                        <p class=" label label-danger">
                            {{ form.errors }}
                        </p>
                    {% endif %}
                    <input type="image" name="submit" value="Add To Favourites" src="{% static 'img/heart.png' %}" width="20" />
                </form>
            </div>

        </div>
      </div>
  </div>
  <br><br><br>
{% endblock %}